###########################################################
# This file is part of the DeadHorses plugin by EasyMFnE. #
###########################################################

# GENERAL SETTINGS
##################

# Whether to allow DeadHorses to be equipped with barding (armor).
armor:
  skeleton_horse: true
  undead_horse: true

# Whether feeding a DeadHorse can age it from a baby to an adult.
feeding-can-age: true

# Whether leads can be used on DeadHorses.
leashing: true

# Whether to modify DeadHorse metadata packets to include armor value.
packet-modification: false

# Whether DeadHorses can be tamed using each method.
taming:
  vanilla-like: true
  food-based: true


# FEEDING SETTINGS
##################
# items are case-insensitive, but must match org.bukkit.Material
# items can be defined with specific datavalues like:
#   'golden_apple:1': 100.0
# chances are in terms of percent (i.e. 0.0-100.0)

skeleton_horse:
  spider_eye: 2.5
  fermented_spider_eye: 5.0
  poisonous_potato: 10.0
undead_horse:
  raw_beef: 10.0
  pork: 5.0
  raw_chicken: 2.5
  raw_fish: 1.25
